name: CI Pipeline

on:
  pull_request:
    branches: [ main, dev-env ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Build & Test with Maven
        run: mvn clean package -DskipTests=false

      - name: Run Tests
        run: mvn test

      - name: Build Docker Image
        run: docker build -t myapp:latest .

